### ISSUE TITLE
aadHttpClientFactory.getClient stopped working

### ISSUE THREAD

**Issue by gianlud4s** [SharePoint/sp-dev-fx-extensions#265] opened 2019-10-29 18:44 UTC
## Category

- [] Question
- [x] Bug
- [] Enhancement

## Expected or Desired Behavior

I'm calling an http trigger azure function protected by AzureAD authentication with the following code:

```
this.context.aadHttpClientFactory.getClient(adAppId).then((client: AadHttpClient): void => {
        client.post(apiUrl, AadHttpClient.configurations.v1, postOptions).then((mailResponse: HttpClientResponse) => {          
        }).catch(error => {
          reject("Error sending email " + error);
        });
      }, err => reject(err));
```

this.context is of type ListViewCommandSetContext.

## Observed Behavior

I got this error `TypeError: Cannot read property 'call' of undefined` when it tries to execute client.post(apiUrl, AadHttpClient.configurations.v1, postOptions).

The extension was already tested and installed, everything was working fine until today and nothing has changed in the extension code. The azure function and the app registration used for the authentication didn't changed too.

The framework version is 1.9.1

Thanks

**Comment by andygjones-nz** [comment] 2019-10-29 22:30
I'm experiencing the same issue with an extension that was previously working fine. Experiencing in 2 seperate tenants.

**Comment by PeppeDotNet** [comment] 2019-10-30 10:31
Same here, using an Application Customizer. 
We are stuck by this error in the production environment...

**Comment by ozie02** [comment] 2019-12-17 04:11
I am experiencing the same issue; my SPFX extension based on 1.9.1 build's successfully, but when the API call initiated to my Azure Function that uses AAD authentication, I end up with the error 

> Cannot read property 'getClient' of undefined

My code is as per the below, 

```
const functionUrl: string = 'https://<URL>';
const cobAadFunctionsAppClientId: string = 'https://<URL>/api/Get';

  public getCurrentUser(): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      this.context.aadHttpClientFactory
        .getClient(cobAadFunctionsAppClientId)
        .then((client: AadHttpClient) => {
          client.get(functionUrl, AadHttpClient.configurations.v1)
          .then((response: HttpClientResponse) => {
            return response.json();
          })
          .then((jsonResponse: any) => {
            resolve(jsonResponse);
          })
          .catch((error) => {
            reject(error);
          });
        });
    });
  }
```
Developer in the ticket below had similar issues then reported that it's fixed. I cant figure out how it was fixed
[The issue with calling Azure AD secured API by using AadHttpClient. #4840](https://github.com/SharePoint/sp-dev-docs/issues/4840)

**Comment by andrewconnell** [comment] 2019-12-17 10:08
@ozie02 Need to see more of your code... that error says `aadHttpClientFactory` is undefined.

There's also an issue with your code... you aren't using the correct client ID when you call `getClient()`. You do not use the full URL to the endpoint. This should be the URI of the resource, like this:

![image](https://user-images.githubusercontent.com/2068657/70985829-cae80380-208a-11ea-854b-dae23e9eb013.png)

The issue you reference also used the wrong value for this method. As I mentioned in that one, you shouldn't use the GUID for the URI of the URL.

**Comment by andrewconnell** [comment] 2019-12-17 10:09
@gianlud4s this is a dupe of #4840... that issue was resolved.

**Closed by andrewconnell** 2019-12-17 10:09 UTC
Labels: Needs: Triage :mag:

**Comment by ozie02** [comment] 2019-12-17 13:03
@andrewconnell appreciate your instant response; the error wasn't clear to me that it might be related to my client ID and URI URL configuration. I will reevaluate my Azure function configuration and try to figure out the solution.

Many thanks

**Comment by ozie02** [comment] 2020-01-11 14:50
Apologies for taking this long. I went back and figured out what could have been wrong with either my code or my Windows Azure Function hosting configuration. Back then, the issue was related to attempting to consume **this.content** object from a child component, which didn't extend **BaseApplicationCustomizer**.

So now, I am passing this.context from the Root component which extends BaseApplicationCustomizer to the child component (Root --> ReactHeader --> ReactPanel --> ReactOrders) which requires to make authentication and the API call. Unfortunately, I am still facing the same issue, I have seen other examples about this working but all of them are implemented as a Webpart rather than an Extension.

I have uploaded my two sample codes. The first example is a webpart consuming my Azure Function and rendering data accordingly (this is to ensure the web service configuration is healthy) and the second example I have an Extension attempting to use the same web service via child component but failing to authenticate.

On the other hand, for some reason after upgrading the extension to SPFX 1.9.1, the generated files are showing in the source folders.

Webpart Source Code: [https://github.com/ozie02/Learning/tree/master/Webpart/contoso-api](url)  
Extension Source Code: [https://github.com/ozie02/Learning/tree/master/Extensions/contoso-api-extension](url) 

I appreciate it in advance if anyone could help?
