### ISSUE TITLE
Build your first extension fails

### ISSUE THREAD

**Issue by giuleon** [SharePoint/sp-dev-fx-extensions#2] opened 2017-06-08 09:14 UTC
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
According with this get started:
https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions 
after the command gulp serve I have the following error:

Error - [write-manifests] Manifest validation error (./src/extensions/appCustomizerHelloWorld/AppCustomizerHelloWorldApplicationCustomizer.manifest.json):
(#/) Data does not match any schemas from 'oneOf'
(#/) Missing required property: description
(#/alias) String is too long (44 chars), maximum 40
(#/componentType) No enum match for: Extension
(#/) Missing required property: preconfiguredEntries
(#/) Missing required property: commands

#### Observed Behavior
After the scaffolding I have to be able to run the client side web part

#### Steps to Reproduce
Please follow these guidelines:
https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/build-a-hello-world-extension
https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions

Thanks for your contribution! Sharing is caring.

**Comment by giuleon** [comment] 2017-06-08 09:34
The problem is caused by the alias in the manifest, after that I changed it with a shorter name everything worked as expected.

**Comment by VesaJuvonen** [comment] 2017-06-11 14:32
thx Giuliano, alias entry does indeed have to be less than 40 characters long. If you follow up on the tutorial, you should get alias as 'HelloWorldApplicationCustomizer', which does not have issues (31 chars). I'll add though a note on the tutorial around this to avoid similar issues for others, so thanks for sharing the input. Closing this for now, since the issue is solved.

**Closed by VesaJuvonen** 2017-06-11 14:32 UTC

**Comment by karthikmakam** [comment] 2019-04-07 03:40
Hi,
I am trying to create a new React Carousel Webpart when i check the gulp serve i am facing below issues:
Error - [write-manifests] Manifest validation error (./src/webparts/reactCarousel/ReactCarouselWebPart.manifest.json):
(#/) Data does not match any schemas from 'oneOf'
(#/) Missing required property: description
(#/) Missing required property: extensionType
(#/componentType) No enum match for: WebPart
(#/) Additional properties not allowed: supportedHosts
(#/) Missing required property: items
(#/) Missing required property: rootComponentId

Kindly provide any help/suggestions.

**Comment by ymihir** [comment] 2019-06-27 18:54
@karthikmakam , same issue for me also. Did you resolved this?
