### ISSUE TITLE
Ts loader not working

### ISSUE THREAD

**Issue by TaurahSP** [SharePoint/sp-dev-fx-extensions#189] opened 2019-01-08 07:48 UTC
I have change the entry point in config.json to a ts file as below:

{
  "version": "2.0",
  "bundles": {
    "site-breadcrumb-bundle": {
      "components": [{
        "entrypoint": "./src/extensions/siteBreadcrumb/SiteBreadcrumbApplicationCustomizer.ts",
        "manifest": "./src/extensions/siteBreadcrumb/SiteBreadcrumbApplicationCustomizer.manifest.json"
      }]
    }
  },
  "localizedResources": {
    "siteBreadcrumbStrings": "./src/extensions/siteBreadcrumb/loc/{locale}.js"
  },
  "externals": {}
}

I get the following error now.

./src/extensions/siteBreadcrumb/SiteBreadcrumbApplicationCustomizer.ts
Module parse failed: C:\Users\username\Projets\26_name\Code\Breadcrumb\sp-dev-fx-extensions\samples\react-application-breadcrumb\src\extensions\siteBreadcrumb\SiteBreadcrumbApplicationCustomizer.ts Unexpected token (15:16)
You may need an appropriate loader to handle this file type.
| import { ISiteBreadcrumbProps } from './components/ISiteBreadcrumb';
|
| const LOG_SOURCE: string = 'SiteBreadcrumbApplicationCustomizer';
|
| /**

**Comment by hugoabernier** [comment] 2020-04-12 02:02
Hey @TaurahSP did you ever resolve this issue?

I'll go ahead and close it because the issue is over a year old.

If you're still running into the issue, I encourage you to open a new issue and take the time to fill the issue template, it'll help us route the issue accordingly

**Closed by hugoabernier** 2020-04-12 02:02 UTC
Labels: no-recent-activity, type:invalid
