### ISSUE TITLE
SPFx Extension- The expected placeholder (Bottom) was not found.

### ISSUE THREAD

**Issue by Mani51** [SharePoint/sp-dev-fx-extensions#170] opened 2018-10-16 13:44 UTC
Hi,
![pnp issue](https://user-images.githubusercontent.com/17005401/47019980-f6651a80-d175-11e8-9967-bf1d25fdb272.PNG)

Suddenly SharePoint Modern Site Navigation and Footer is not getting loaded in any of the site pages. Getting the error as "The expected placeholder (Bottom) was not found."

Is there any Microsoft update going on? 

Please help me!

Thanks

**Comment by Cyan005** [comment] 2018-10-16 14:31
I can confirm that as of late last week, this also started popping up in our tenant. Our extensions have been working with no issues for over a month.

Also, it seems that on the applications pages (or site contents), the extension works just fine.  I'm also seeing console log messages from spofiles indicating "Defined clientSidePlaceholders: DialogContainer,Top,Bottom".  I don't recall seeing these before.  

We're trying to put some changes in to see if we can make them work, but certainly something happened which triggered this.

**Comment by Cyan005** [comment] 2018-10-16 15:15
@Mani51 Just an update here, we added some code to the solution and upon some quick testing, the extension seems to be loading as expected:

```
// Added to handle possible changes on the existence of placeholders.
this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);
```

This was found over at https://github.com/SharePOint/sp-dev-docs/issues/1042

**Comment by Cyan005** [comment] 2018-10-16 15:44
> @Mani51 Just an update here, we added some code to the solution and upon some quick testing, the extension seems to be loading as expected:
> 
> ```
> // Added to handle possible changes on the existence of placeholders.
> this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);
> ```
> This was found over at [SharePoint/sp-dev-docs#1042](https://github.com/SharePoint/sp-dev-docs/issues/1042)

And this apparently wasn't the solution, starting to see the same issue again after deployment.

**Comment by harshdamaniahd** [comment] 2018-10-18 07:32
I guess now its working.
Pls try

**Comment by BigEaseGueldi** [comment] 2018-10-19 07:29
It's not. Since this morning, placeholders are not found anymore.

**Comment by harshdamaniahd** [comment] 2018-10-19 09:56
I was facing this issue two days back, and then it got fixed on its own.
Strange

**Comment by BigEaseGueldi** [comment] 2018-10-19 11:18
We're still facing this issue. On different tenants.

**Comment by Cyan005** [comment] 2018-10-19 13:33
> I was facing this issue two days back, and then it got fixed on its own.
> Strange

Yeah I haven't noticed the issue the last few days.  Something 'magical' happened to fix it.

**Comment by pedropablo** [comment] 2018-10-19 20:20
> > I was facing this issue two days back, and then it got fixed on its own.
> > Strange
> 
> Yeah I haven't noticed the issue the last few days. Something 'magical' happened to fix it.

I added the **changedevent** you suggested and is now working. But I'm not sure if that was it or some internal SharePoint magic did the trick. 

BTW that line is on the official documentation of the extensions. Not sure when it was added, my code is a bit old and was working fine until this week ¯\_(ツ)_/¯

**Comment by harshdamaniahd** [comment] 2018-10-20 08:10
https://github.com/SharePoint/sp-dev-docs/wiki/Safely-using-Placeholders-in-an-extension
Please read this article.

**Comment by hugoabernier** [comment] 2020-04-12 01:52
@Mani51 did @harshdamaniahd 's suggestion ever help you solve the issue?

I'll close the issue, but feel free to open a new issue if you still need more help.

Thanks @harshdamaniahd  for your help!

**Closed by hugoabernier** 2020-04-12 01:52 UTC
Labels: status:answered
