### ISSUE TITLE
Error when running extensions : Killswitches are not initialized

### ISSUE THREAD

**Issue by veeramanx** [SharePoint/sp-dev-fx-extensions#112] opened 2018-03-14 13:12 UTC
I am getting an following error while running application cutomiser extension 

ERROR:
Killswitches are not initialized. Killswitch requested: aca19dad-e178-47bd-882e-5633af7b7ff0

can you let me know what is it?

**Comment by jcosta3394** [comment] 2018-03-14 18:16
I'm getting the same error, I started removing sections of my project and nothing seemed to work until I finally just **started a new vanilla extension**, ran gulp serve **and the same error was still there**.

Here's the full log:

ERROR:
Killswitches are not initialized. Killswitch requested: aca19dad-e178-47bd-882e-5633af7b7ff0

CALL STACK:
Error: Killswitches are not initialized. Killswitch requested: aca19dad-e178-47bd-882e-5633af7b7ff0
    at Function.e.isActivated (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-core-library_en-us_7572ea1dfcf36c9fe486c603f1fb4180.js:70:14914)
    at t._forEachPropertyWithMetaData (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-webpart-base_en-us_6f37be4345fbc42c528567e61dc58d6f.js:84:25477)
    at t._reInstateServerProcessedData (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-webpart-base_en-us_6f37be4345fbc42c528567e61dc58d6f.js:84:24160)
    at t._deserialize (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-webpart-base_en-us_6f37be4345fbc42c528567e61dc58d6f.js:84:27069)
    at t._internalDeserialize (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-webpart-base_en-us_6f37be4345fbc42c528567e61dc58d6f.js:84:28284)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-webpart-base_en-us_6f37be4345fbc42c528567e61dc58d6f.js:84:29330
    at new Promise (<anonymous>)
    at t._internalFirstTimeRender (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-webpart-base_en-us_6f37be4345fbc42c528567e61dc58d6f.js:84:28874)
    at e._initializeAndRenderWebPart (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-pages-assembly_en-us_df1645f6671d8b670ea06ba191d8f267.js:428:73263)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-02.011/sp-pages-assembly_en-us_df1645f6671d8b670ea06ba191d8f267.js:428:59061

**Comment by jcosta3394** [comment] 2018-03-15 10:34
I just noticed this morning that the problem seems to have been fixed, thanks!

**Comment by tdwhite0** [comment] 2018-03-15 18:28
This problem is showing up for me today.

**Comment by jcosta3394** [comment] 2018-03-15 18:33
The problem is back, are you guys working on a new build atm?

**Comment by veeramanx** [comment] 2018-03-16 15:51
Hi, i also have the same issue today

**Comment by mpasarin** [comment] 2018-03-16 16:46
Thank you for your feedback.

I have a few questions about this problem that could help us investigate.
Does this problem happen using application customizers on pages, lists, or
both?
If it's on pages, are you trying with an empty page, or a page with web
parts?
What does the extension do? Or are you just trying the code that just comes
from the Yeoman generator?

**Comment by veeramanx** [comment] 2018-03-20 10:50
Hi mpasarin,
the problem happening using application uctomiser on pages. I am trying on both empty page and with webparts. 
I am trying to check if user page exist or not.

**Comment by mpasarin** [comment] 2018-03-20 16:45
This is caused by a problem on our side in the last version. We are working
on a fix and it should be rolled out pretty soon.

In the meantime, please use lists to debug your application customizers, as
they are not affected by this problem.

**Comment by veeramanx** [comment] 2018-03-20 17:20
ok thanks mpasarin.

**Comment by mpasarin** [comment] 2018-03-20 20:32
Actually the fix was being rolled out as I replied in the thread. It should
be working now.

**Comment by VesaJuvonen** [comment] 2018-03-21 12:05
Hi @veeramanx, @jcosta3394 or @tdwhite0, we would appreciate an acknowledgment that you don't see this issue anymore so that we can close this issue.

In general, when you find any potential issues on SPFx in general (not on samples), we recommend to report them at http://aka.ms/spdev-issues, so that your issue will be processed as fast as possible. That is the centralized issue list for SP dev topics which we triage for engineering actions.

**Comment by jcosta3394** [comment] 2018-03-21 12:08
Hi @VesaJuvonen, I apologize for the late reply. Yes, the issue seems to be fixed, thank you!

**Comment by VesaJuvonen** [comment] 2018-03-21 12:18
thx José, appreciated. Closing this from here.

**Closed by VesaJuvonen** 2018-03-21 12:18 UTC
Labels: Waiting for input
