### ISSUE TITLE
react-application-tenant-global-navbar - is removed after using the search page

### ISSUE THREAD

**Issue by yvonne70** [SharePoint/sp-dev-fx-extensions#73] opened 2017-11-22 16:19 UTC
react-application-tenant-global-navbar
Category - Bug

Expected or Desired Behavior
The navbar is still visible on the page after the user navigates back from using the search page.

Observed Behavior
The Nav Bar disappears from the page when I navigate back from using the search page (new experinence).

Steps to Reproduce

- Search in the left hand search box and click on 'Show more results'

- Your are now in the new experience search results page.

- Now click on the arrow on the left side (next to the Search term you entered)

- When you are back on the page from which you performed the search the navbar is now missing.

**Comment by VesaJuvonen** [comment] 2018-03-16 15:09
As this is a generic issue and not specific to the samples, will close this from here. This is a duplicate of https://github.com/SharePoint/sp-dev-docs/issues/1042, which should be resolved soon.

**Closed by VesaJuvonen** 2018-03-16 15:09 UTC
