### ISSUE TITLE
SPFx Extension Header flicker Issue.

### ISSUE THREAD

**Issue by vivekdhanuka2002** [SharePoint/sp-dev-fx-extensions#128] opened 2018-04-30 09:40 UTC
> SPFx Extension Header flicker Issue. 
> ----
> To customize the Header we have used sharepoint extension model. Its Working but there is a Flicker in loading.
It Loads the Old Header (By Default header provided in modern pages) and then my extension work.

## Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

## Expected or Desired Behavior

> Extension should load without Flicker
> 

## Observed Behavior

>To customize the Header we have used sharepoint extension model. Its Working but there is a Flicker in loading.
It Loads the Old Header (By Default header provided in modern pages) and then my extension work.

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment] 2018-06-12 07:58
This is currently by design due to the load timings. We are working on reducing the flicker with the future versions, but there's no easy fix for this for now.

**Closed by VesaJuvonen** 2018-06-12 07:58 UTC
